def f1(request):
	return HttpResponse('f1...')
def f2(request):
	return HttpResponse('f2...')
def f3(request):
	return HttpResponse('f3...')
def f4(request):
	return HttpResponse('f4...')
def f5(request):
	return HttpResponse('f5...')
def f6(request):
	return HttpResponse('f6...')
